# coding: utf-8
require 'open-uri'
require 'nokogiri'
require 'date'
require 'csv'
require 'jpstock/base'
require 'jpstock/price'
require 'jpstock/historicalprices'
require 'jpstock/sector'
require 'jpstock/quote'
require 'jpstock/nipd'
require 'jpstock/tdnet'
require 'jpstock/edinet'
require 'jpstock/credit'
